WaterA1Frame0:
; Tile index $000
.db $80 $00 $80 $80 $E0 $80 $E0 $E0 $7C $E0 $FC $FC $1F $FC $FF $FF $C3 $FF $FF $FF $00 $FF $FF $FF $C0 $FF $FF $FF $39 $FF $FF $FF
; Tile index $001
.db $01 $00 $01 $01 $07 $01 $07 $07 $3E $07 $3F $3F $F8 $3F $FF $FF $C0 $FF $FF $FF $0E $F3 $FF $FF $79 $8F $FF $FF $E0 $FF $FF $FF

WaterA1Frame1:
; Tile index $002
.db $00 $00 $00 $00 $98 $00 $98 $98 $FF $18 $FF $FF $E7 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $E0 $FF $FF $FF $1F $FF $FF $FF
; Tile index $003
.db $0A $00 $0A $0A $1F $00 $1F $1F $0B $00 $0B $0B $FF $01 $FF $FF $FE $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $57 $FF $FF $FF

WaterA1Frame2:
; Tile index $004
.db $00 $00 $00 $00 $1A $00 $1A $1A $FF $18 $FF $FF $E7 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $E0 $FF $FF $FF $1F $FF $FF $FF
; Tile index $005
.db $58 $00 $58 $58 $04 $00 $04 $04 $01 $00 $01 $01 $FF $01 $FF $FF $FE $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $57 $FF $FF $FF

WaterA1Frame3:
; Tile index $006
.db $09 $00 $09 $09 $00 $00 $00 $00 $01 $00 $01 $01 $FF $01 $FF $FF $FE $FF $FF $FF $60 $FF $FF $FF $0E $FF $FF $FF $FC $FF $FF $FF
; Tile index $007
.db $80 $00 $80 $80 $40 $00 $40 $40 $E0 $00 $E0 $E0 $FF $E0 $FF $FF $1F $FF $FF $FF $00 $FF $FF $FF $0E $FF $FF $FF $87 $FF $FF $FF

WaterA1Frame4:
; Tile index $008
.db $00 $00 $00 $00 $08 $00 $08 $08 $01 $00 $01 $01 $FF $01 $FF $FF $FE $FF $FF $FF $60 $FF $FF $FF $0E $FF $FF $FF $FC $FF $FF $FF
; Tile index $009
.db $00 $00 $00 $00 $00 $00 $00 $00 $E0 $00 $E0 $E0 $FF $E0 $FF $FF $1F $FF $FF $FF $00 $FF $FF $FF $0E $FF $FF $FF $87 $FF $FF $FF

WaterA1Frame5:
; Tile index $00A
.db $00 $00 $00 $00 $2C $00 $2C $2C $10 $00 $10 $10 $FF $00 $FF $FF $FF $FF $FF $FF $00 $FF $FF $FF $01 $FF $FF $FF $8E $FF $FF $FF
; Tile index $00B
.db $00 $00 $00 $00 $18 $00 $18 $18 $FF $18 $FF $FF $E7 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $E0 $FF $FF $FF $1E $FF $FF $FF

WaterA1Frame6:
; Tile index $00C
.db $00 $00 $00 $00 $82 $00 $82 $82 $00 $00 $00 $00 $FF $00 $FF $FF $FF $FF $FF $FF $00 $FF $FF $FF $01 $FF $FF $FF $8E $FF $FF $FF
; Tile index $00D
.db $00 $00 $00 $00 $18 $00 $18 $18 $FF $18 $FF $FF $E7 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $E0 $FF $FF $FF $1E $FF $FF $FF

WaterA1Frame7:
; Tile index $00E
.db $80 $00 $80 $80 $E0 $80 $E0 $E0 $7D $E0 $FD $FD $1F $FC $FF $FF $C3 $FF $FF $FF $00 $FF $FF $FF $C0 $FF $FF $FF $39 $FF $FF $FF
; Tile index $00F
.db $01 $00 $01 $01 $07 $01 $07 $07 $3E $07 $3F $3F $F8 $3F $FF $FF $C0 $FF $FF $FF $0E $F3 $FF $FF $79 $8F $FF $FF $E0 $FF $FF $FF
