LavaFrame0:
; Tile index $000
.db $D7 $28 $28 $28 $E7 $10 $18 $18 $EF $00 $10 $10 $FF $00 $00 $00 $00 $FF $FF $FF $38 $C6 $FF $C7 $00 $78 $FF $FF $00 $27 $FF $FF
; Tile index $001
.db $0C $F2 $FF $F3 $01 $20 $FF $FE $80 $00 $FF $7F $C3 $00 $FF $3C $E7 $00 $FF $18 $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $FF $00
; Tile index $002
.db $FF $00 $00 $00 $C7 $00 $38 $38 $A2 $19 $6D $7D $01 $78 $8E $FE $00 $91 $FF $FF $82 $01 $FF $7D $7C $00 $FF $83 $00 $9E $FF $FF
; Tile index $003
.db $00 $00 $FF $FF $B0 $00 $FF $4F $E0 $00 $FF $1F $83 $00 $FF $7C $C7 $00 $FF $38 $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $FF $00

LavaFrame1:
; Tile index $004
.db $3F $80 $C0 $C0 $7E $01 $81 $81 $F6 $08 $09 $09 $FF $00 $00 $00 $00 $FF $FF $FF $00 $CE $FF $FF $00 $79 $FE $FF $01 $26 $FD $FF
; Tile index $005
.db $0C $F3 $FF $F3 $04 $20 $FF $FB $03 $00 $FF $FC $87 $00 $FF $78 $CF $00 $FF $30 $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $FF $00
; Tile index $006
.db $EF $10 $10 $10 $7D $82 $82 $82 $3B $44 $FC $C4 $13 $28 $FE $EC $06 $B1 $FF $F9 $86 $21 $FF $79 $7C $80 $FF $83 $20 $C6 $FF $DF
; Tile index $007
.db $30 $00 $FF $CF $30 $00 $FF $CF $E2 $00 $FF $1D $06 $00 $FF $F9 $8F $00 $FF $70 $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $FF $00

LavaFrame2:
; Tile index $008
.db $BD $40 $42 $42 $F8 $02 $07 $07 $BD $40 $42 $42 $CF $30 $30 $30 $00 $FF $FF $FF $01 $7E $FF $FE $03 $30 $FF $FC $01 $E6 $FD $FE
; Tile index $009
.db $0C $33 $FE $F3 $04 $00 $FF $FB $E3 $00 $FF $1C $40 $00 $FF $BF $F7 $00 $FF $08 $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $FF $00
; Tile index $00A
.db $D7 $28 $28 $28 $EF $10 $10 $10 $EF $10 $10 $10 $5F $20 $A0 $A0 $00 $BF $FF $FF $B8 $07 $FF $47 $40 $80 $7F $BF $20 $C6 $7F $DF
; Tile index $00B
.db $30 $80 $FF $CF $30 $00 $FF $CF $E0 $00 $FF $1F $00 $00 $FF $FF $E2 $00 $FF $1D $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $FF $00

LavaFrame3:
; Tile index $00C
.db $FF $00 $00 $00 $DD $22 $22 $22 $FF $00 $00 $00 $CF $00 $30 $30 $00 $A3 $FF $FF $48 $04 $FB $B7 $32 $04 $FF $CD $01 $C6 $FD $FE
; Tile index $00D
.db $04 $03 $FE $FB $C3 $00 $FF $3C $B0 $00 $FF $4F $C3 $00 $FF $3C $9F $00 $FF $60 $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $FF $00
; Tile index $00E
.db $FD $02 $02 $02 $F8 $06 $07 $07 $FD $00 $02 $02 $7D $00 $82 $82 $00 $BD $FF $FF $00 $27 $DF $FF $90 $6C $BF $6F $00 $C1 $7F $FF
; Tile index $00F
.db $40 $87 $FF $BF $80 $00 $FF $7F $0C $00 $FF $F3 $06 $00 $FF $F9 $8F $00 $FF $70 $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $FF $00

LavaFrame4:
; Tile index $010
.db $FD $02 $02 $02 $FF $00 $00 $00 $FF $00 $00 $00 $DF $00 $30 $20 $08 $26 $FD $F7 $58 $01 $FE $A7 $30 $05 $FE $CF $00 $CA $FF $FF
; Tile index $011
.db $03 $00 $FF $FC $00 $00 $FF $FF $61 $00 $FF $9E $C1 $00 $FF $3E $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $FF $00
; Tile index $012
.db $FD $02 $02 $02 $FF $00 $00 $00 $EF $10 $10 $10 $6F $10 $90 $90 $00 $BF $7F $FF $00 $27 $DF $FF $80 $4C $FF $7F $00 $F1 $FF $FF
; Tile index $013
.db $80 $37 $FF $7F $00 $00 $FF $FF $06 $00 $FF $F9 $81 $00 $FF $7E $E3 $00 $FF $1C $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $FF $00

LavaFrame5:
; Tile index $014
.db $FF $00 $00 $00 $FF $00 $00 $00 $FE $01 $01 $01 $63 $80 $9C $9C $01 $98 $EE $FE $22 $80 $FF $DD $1C $00 $FF $E3 $00 $C3 $FF $FF
; Tile index $015
.db $00 $77 $FF $FF $0C $00 $FF $F3 $17 $00 $FF $E8 $A3 $00 $FF $5C $C7 $00 $FF $38 $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $FF $00
; Tile index $016
.db $FF $00 $00 $00 $FF $00 $00 $00 $EA $05 $15 $15 $C7 $10 $38 $38 $00 $8F $FF $FF $00 $DF $FF $FF $00 $70 $FF $FF $00 $9E $FF $FF
; Tile index $017
.db $00 $68 $FF $FF $00 $1E $FF $FF $00 $00 $FF $FF $81 $00 $FF $7E $8F $00 $FF $70 $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $FF $00

LavaFrame6:
; Tile index $018
.db $FF $00 $00 $00 $FF $00 $00 $00 $E2 $01 $1D $1D $41 $88 $BE $BE $00 $BC $E7 $FF $41 $80 $FF $BE $3F $00 $FF $C0 $00 $C1 $FF $FF
; Tile index $019
.db $00 $79 $FF $FF $71 $00 $FF $8E $F8 $00 $FF $07 $4C $00 $FF $B3 $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $FF $00
; Tile index $01A
.db $FF $00 $00 $00 $FF $00 $00 $00 $EA $05 $15 $15 $C7 $10 $38 $38 $00 $8F $FF $FF $00 $DF $FF $FF $80 $70 $FF $7F $60 $9E $FF $9F
; Tile index $01B
.db $40 $28 $FF $BF $10 $00 $FF $EF $E0 $00 $FF $1F $01 $00 $FF $FE $E3 $00 $FF $1C $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $FF $00

LavaFrame7:
; Tile index $01C
.db $FF $00 $00 $00 $FF $00 $00 $00 $9C $63 $63 $63 $80 $3E $7F $7F $44 $88 $BF $BB $2E $41 $FF $D1 $1C $03 $FF $E3 $00 $7C $FF $FF
; Tile index $01D
.db $00 $22 $FF $FF $C0 $00 $FF $3F $B0 $00 $FF $4F $C3 $00 $FF $3C $9F $00 $FF $60 $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $FF $00
; Tile index $01E
.db $FE $01 $01 $01 $C3 $04 $3C $3C $83 $38 $5C $7C $01 $12 $FE $FE $44 $83 $FF $BB $38 $C1 $FF $C7 $00 $80 $FF $FF $00 $E3 $FF $FF
; Tile index $01F
.db $00 $50 $FF $FF $40 $00 $FF $BF $01 $00 $FF $FE $03 $00 $FF $FC $8F $00 $FF $70 $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $FF $00
